// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotMarket.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotMarket.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260903113755_AddNotePdfGenerationArtifactCache")]
    partial class AddNotePdfGenerationArtifactCache
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotMarket.Api.Domain.AcademicProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademicUnitId")
                        .HasColumnType("uuid");

                    b.Property<string>("CatalogKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CatalogVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DegreeLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EducationLanguage")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSelectable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("LastVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("SourceName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CatalogKey")
                        .IsUnique();

                    b.HasIndex("AcademicUnitId", "IsActive");

                    b.HasIndex("AcademicUnitId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("AcademicUnitId", "IsActive", "IsSelectable");

                    b.ToTable("AcademicPrograms", (string)null);
                });

            modelBuilder.Entity("NotMarket.Api.Domain.AcademicUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CatalogKey")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("CatalogVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("SourceName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CatalogKey")
                        .IsUnique();

                    b.HasIndex("UniversityId", "IsActive");

                    b.HasIndex("UniversityId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("AcademicUnits", (string)null);
                });

            modelBuilder.Entity("NotMarket.Api.Domain.AcademicUniversity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CatalogKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CatalogVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("SourceName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CatalogKey")
                        .IsUnique();

                    b.HasIndex("CountryCode", "IsActive");

                    b.HasIndex("CountryCode", "NormalizedName")
                        .IsUnique();

                    b.ToTable("AcademicUniversities", (string)null);
                });

            modelBuilder.Entity("NotMarket.Api.Domain.AcademicUniversityAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedAlias")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedAlias")
                        .IsUnique();

                    b.HasIndex("UniversityId");

                    b.ToTable("AcademicUniversityAliases", (string)null);
                });

            modelBuilder.Entity("NotMarket.Api.Domain.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NotMarket.Api.Domain.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailsJson")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("NotMarket.Api.Domain.NoteAiReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConfidenceScore")
                        .HasColumnType("integer");

                    b.Property<int>("ContentCompletenessScore")
                        .HasColumnType("integer");

                    b.Property<int>("CourseMatchScore")
                        .HasColumnType("integer");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("DepartmentMatchScore")
                        .HasColumnType("integer");

                    b.Property<string>("DetectedCourse")
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<string>("DetectedDepartment")
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<string>("FindingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsTechnicallyValid")
                        .HasColumnType("boolean");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("NoteSubmissionId")
                        .HasColumnType("uuid");

                    b.Property<int>("OriginalityAndReliabilityScore")
                        .HasColumnType("integer");

                    b.Property<int>("OriginalityRiskScore")
                        .HasColumnType("integer");

                    b.Property<int>("OverallScore")
                        .HasColumnType("integer");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ReadabilityScore")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Decision", "ReviewedAt");

                    b.HasIndex("NoteSubmissionId", "ReviewedAt");

                    b.ToTable("NoteAiReviews", null, t =>
                        {
                            t.HasCheckConstraint("CK_NoteAiReviews_ScoresRange", "\"ReadabilityScore\" BETWEEN 0 AND 100 AND \"CourseMatchScore\" BETWEEN 0 AND 100 AND \"DepartmentMatchScore\" BETWEEN 0 AND 100 AND \"ContentCompletenessScore\" BETWEEN 0 AND 100 AND \"OriginalityAndReliabilityScore\" BETWEEN 0 AND 100 AND \"OriginalityRiskScore\" BETWEEN 0 AND 100 AND \"OverallScore\" BETWEEN 0 AND 100 AND \"ConfidenceScore\" BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("NotMarket.Api.Domain.NotePdfGenerationArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ConvertedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentModelJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("LatexSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("NoteSubmissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("RenderedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceDocumentSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TemplateVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NoteSubmissionId")
                        .IsUnique();

                    b.HasIndex("SourceDocumentSha256");

                    b.ToTable("NotePdfGenerationArtifacts", (string)null);
                });

            modelBuilder.Entity("NotMarket.Api.Domain.NoteRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<int>("ClassLevel")
                        .HasColumnType("integer");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriteriaJson")
                        .IsRequired()
                        .HasMaxLength(1400)
                        .HasColumnType("character varying(1400)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<decimal>("SuggestedMaxPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SuggestedMinPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("UniversityName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.HasKey("Id");

                    b.ToTable("NoteRequests");
                });

            modelBuilder.Entity("NotMarket.Api.Domain.NoteSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeneratedPdfBlobPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("MatchScore")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalBlobPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OriginalityRiskScore")
                        .HasColumnType("integer");

                    b.Property<string>("PdfCompilerName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PdfConversionPromptVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("PdfGeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PdfGenerationAttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("PdfGenerationError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PdfGenerationModelName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PdfTemplateVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ReadabilityScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("SalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.HasIndex("SellerId");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("NoteSubmissions", null, t =>
                        {
                            t.HasCheckConstraint("CK_NoteSubmissions_PdfGenerationAttemptCount", "\"PdfGenerationAttemptCount\" >= 0");

                            t.HasCheckConstraint("CK_NoteSubmissions_SalePrice", "\"SalePrice\" IS NULL OR \"SalePrice\" > 0");
                        });
                });

            modelBuilder.Entity("NotMarket.Api.Domain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("GrossAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("NoteSubmissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("NoteTitleSnapshot")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PlatformCommissionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("SellerEarningAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("NoteSubmissionId");

                    b.HasIndex("BuyerId", "NoteSubmissionId")
                        .IsUnique()
                        .HasFilter("\"Status\" IN ('PendingPayment', 'Paid')");

                    b.HasIndex("BuyerId", "Status");

                    b.HasIndex("SellerId", "Status");

                    b.ToTable("Orders", null, t =>
                        {
                            t.HasCheckConstraint("CK_Orders_AmountBalance", "\"GrossAmount\" = \"PlatformCommissionAmount\" + \"SellerEarningAmount\"");

                            t.HasCheckConstraint("CK_Orders_DifferentUsers", "\"BuyerId\" <> \"SellerId\"");

                            t.HasCheckConstraint("CK_Orders_PositiveAmounts", "\"GrossAmount\" > 0 AND \"PlatformCommissionAmount\" >= 0 AND \"SellerEarningAmount\" >= 0");
                        });
                });

            modelBuilder.Entity("NotMarket.Api.Domain.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProviderPaymentId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("ProviderPaymentId")
                        .IsUnique();

                    b.ToTable("Payments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Payments_PositiveAmount", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("NotMarket.Api.Domain.SiteVisit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("SessionHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("VisitedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("VisitedAt");

                    b.HasIndex("SessionHash", "Path", "VisitedAt");

                    b.ToTable("SiteVisits");
                });

            modelBuilder.Entity("NotMarket.Api.Domain.StudentVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AcademicProgramId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AcademicUnitId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentBlobPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DocumentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateOnly>("DocumentIssueDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UniversityId")
                        .HasColumnType("uuid");

                    b.Property<string>("UniversityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AcademicProgramId");

                    b.HasIndex("AcademicUnitId");

                    b.HasIndex("DocumentHash")
                        .IsUnique();

                    b.HasIndex("UniversityId");

                    b.HasIndex("UserId", "UniversityId", "AcademicUnitId", "AcademicProgramId", "Status");

                    b.ToTable("StudentVerifications");
                });

            modelBuilder.Entity("NotMarket.Api.Domain.AcademicProgram", b =>
                {
                    b.HasOne("NotMarket.Api.Domain.AcademicUnit", "AcademicUnit")
                        .WithMany("Programs")
                        .HasForeignKey("AcademicUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicUnit");
                });

            modelBuilder.Entity("NotMarket.Api.Domain.AcademicUnit", b =>
                {
                    b.HasOne("NotMarket.Api.Domain.AcademicUniversity", "University")
                        .WithMany("AcademicUnits")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("NotMarket.Api.Domain.AcademicUniversityAlias", b =>
                {
                    b.HasOne("NotMarket.Api.Domain.AcademicUniversity", "University")
                        .WithMany("Aliases")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("NotMarket.Api.Domain.NoteAiReview", b =>
                {
                    b.HasOne("NotMarket.Api.Domain.NoteSubmission", "NoteSubmission")
                        .WithMany("AiReviews")
                        .HasForeignKey("NoteSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NoteSubmission");
                });

            modelBuilder.Entity("NotMarket.Api.Domain.NotePdfGenerationArtifact", b =>
                {
                    b.HasOne("NotMarket.Api.Domain.NoteSubmission", "NoteSubmission")
                        .WithOne("PdfGenerationArtifact")
                        .HasForeignKey("NotMarket.Api.Domain.NotePdfGenerationArtifact", "NoteSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NoteSubmission");
                });

            modelBuilder.Entity("NotMarket.Api.Domain.NoteSubmission", b =>
                {
                    b.HasOne("NotMarket.Api.Domain.NoteRequest", "Request")
                        .WithMany("Submissions")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotMarket.Api.Domain.ApplicationUser", "Seller")
                        .WithMany("NoteSubmissions")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("NotMarket.Api.Domain.Order", b =>
                {
                    b.HasOne("NotMarket.Api.Domain.ApplicationUser", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NotMarket.Api.Domain.NoteSubmission", "NoteSubmission")
                        .WithMany("Orders")
                        .HasForeignKey("NoteSubmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NotMarket.Api.Domain.ApplicationUser", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("NoteSubmission");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("NotMarket.Api.Domain.Payment", b =>
                {
                    b.HasOne("NotMarket.Api.Domain.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("NotMarket.Api.Domain.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("NotMarket.Api.Domain.StudentVerification", b =>
                {
                    b.HasOne("NotMarket.Api.Domain.AcademicProgram", "AcademicProgram")
                        .WithMany("StudentVerifications")
                        .HasForeignKey("AcademicProgramId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NotMarket.Api.Domain.AcademicUnit", "AcademicUnit")
                        .WithMany("StudentVerifications")
                        .HasForeignKey("AcademicUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NotMarket.Api.Domain.AcademicUniversity", "University")
                        .WithMany("StudentVerifications")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NotMarket.Api.Domain.ApplicationUser", "User")
                        .WithMany("StudentVerifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicProgram");

                    b.Navigation("AcademicUnit");

                    b.Navigation("University");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NotMarket.Api.Domain.AcademicProgram", b =>
                {
                    b.Navigation("StudentVerifications");
                });

            modelBuilder.Entity("NotMarket.Api.Domain.AcademicUnit", b =>
                {
                    b.Navigation("Programs");

                    b.Navigation("StudentVerifications");
                });

            modelBuilder.Entity("NotMarket.Api.Domain.AcademicUniversity", b =>
                {
                    b.Navigation("AcademicUnits");

                    b.Navigation("Aliases");

                    b.Navigation("StudentVerifications");
                });

            modelBuilder.Entity("NotMarket.Api.Domain.ApplicationUser", b =>
                {
                    b.Navigation("NoteSubmissions");

                    b.Navigation("StudentVerifications");
                });

            modelBuilder.Entity("NotMarket.Api.Domain.NoteRequest", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("NotMarket.Api.Domain.NoteSubmission", b =>
                {
                    b.Navigation("AiReviews");

                    b.Navigation("Orders");

                    b.Navigation("PdfGenerationArtifact");
                });

            modelBuilder.Entity("NotMarket.Api.Domain.Order", b =>
                {
                    b.Navigation("Payment");
                });
#pragma warning restore 612, 618
        }
    }
}
