// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotMarket.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotMarket.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260801123421_AddAcademicUnitsAndPrograms")]
    partial class AddAcademicUnitsAndPrograms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotMarket.Api.Domain.AcademicProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademicUnitId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AcademicUnitId", "IsActive");

                    b.HasIndex("AcademicUnitId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("AcademicPrograms", (string)null);
                });

            modelBuilder.Entity("NotMarket.Api.Domain.AcademicUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId", "IsActive");

                    b.HasIndex("UniversityId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("AcademicUnits", (string)null);
                });

            modelBuilder.Entity("NotMarket.Api.Domain.AcademicUniversity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode", "IsActive");

                    b.HasIndex("CountryCode", "NormalizedName")
                        .IsUnique();

                    b.ToTable("AcademicUniversities", (string)null);
                });

            modelBuilder.Entity("NotMarket.Api.Domain.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NotMarket.Api.Domain.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailsJson")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("NotMarket.Api.Domain.NoteRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<int>("ClassLevel")
                        .HasColumnType("integer");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriteriaJson")
                        .IsRequired()
                        .HasMaxLength(1400)
                        .HasColumnType("character varying(1400)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<decimal>("SuggestedMaxPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SuggestedMinPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("UniversityName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.HasKey("Id");

                    b.ToTable("NoteRequests");
                });

            modelBuilder.Entity("NotMarket.Api.Domain.NoteSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeneratedPdfBlobPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("MatchScore")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalBlobPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OriginalityRiskScore")
                        .HasColumnType("integer");

                    b.Property<int>("ReadabilityScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.HasIndex("SellerId");

                    b.ToTable("NoteSubmissions");
                });

            modelBuilder.Entity("NotMarket.Api.Domain.StudentVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AcademicProgramId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AcademicUnitId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentBlobPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DocumentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateOnly>("DocumentIssueDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UniversityId")
                        .HasMaxLength(180)
                        .HasColumnType("uuid");

                    b.Property<string>("UniversityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AcademicProgramId");

                    b.HasIndex("AcademicUnitId");

                    b.HasIndex("DocumentHash")
                        .IsUnique();

                    b.HasIndex("UniversityId");

                    b.HasIndex("UserId", "UniversityId", "AcademicUnitId", "AcademicProgramId", "Status");

                    b.ToTable("StudentVerifications");
                });

            modelBuilder.Entity("NotMarket.Api.Domain.AcademicProgram", b =>
                {
                    b.HasOne("NotMarket.Api.Domain.AcademicUnit", "AcademicUnit")
                        .WithMany("Programs")
                        .HasForeignKey("AcademicUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicUnit");
                });

            modelBuilder.Entity("NotMarket.Api.Domain.AcademicUnit", b =>
                {
                    b.HasOne("NotMarket.Api.Domain.AcademicUniversity", "University")
                        .WithMany("AcademicUnits")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("NotMarket.Api.Domain.NoteSubmission", b =>
                {
                    b.HasOne("NotMarket.Api.Domain.NoteRequest", "Request")
                        .WithMany("Submissions")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotMarket.Api.Domain.ApplicationUser", "Seller")
                        .WithMany("NoteSubmissions")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("NotMarket.Api.Domain.StudentVerification", b =>
                {
                    b.HasOne("NotMarket.Api.Domain.AcademicProgram", "AcademicProgram")
                        .WithMany("StudentVerifications")
                        .HasForeignKey("AcademicProgramId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NotMarket.Api.Domain.AcademicUnit", "AcademicUnit")
                        .WithMany("StudentVerifications")
                        .HasForeignKey("AcademicUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NotMarket.Api.Domain.AcademicUniversity", "University")
                        .WithMany("StudentVerifications")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NotMarket.Api.Domain.ApplicationUser", "User")
                        .WithMany("StudentVerifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicProgram");

                    b.Navigation("AcademicUnit");

                    b.Navigation("University");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NotMarket.Api.Domain.AcademicProgram", b =>
                {
                    b.Navigation("StudentVerifications");
                });

            modelBuilder.Entity("NotMarket.Api.Domain.AcademicUnit", b =>
                {
                    b.Navigation("Programs");

                    b.Navigation("StudentVerifications");
                });

            modelBuilder.Entity("NotMarket.Api.Domain.AcademicUniversity", b =>
                {
                    b.Navigation("AcademicUnits");

                    b.Navigation("StudentVerifications");
                });

            modelBuilder.Entity("NotMarket.Api.Domain.ApplicationUser", b =>
                {
                    b.Navigation("NoteSubmissions");

                    b.Navigation("StudentVerifications");
                });

            modelBuilder.Entity("NotMarket.Api.Domain.NoteRequest", b =>
                {
                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
